receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    logLevel: debug
    
  # Data sources: traces, metrics, logs
  file:
    path: ./collector.json
    
  tanzuobservability:
    traces:
    #hostname and  'customeTracingListenerPorts' of the Wavefront Proxy
       endpoint: "http://dev-proxy-temp.cyracomdev.com:30001"
       

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, tanzuobservability]
      processors: [batch]
